AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  Serverless stack for automated data processing tasks

Metadata:
  AWS::ServerlessRepo::Application:
    Name: Athena Query execution
    Description: Implementation of Serverless Stack to schedule queries
    Author: Jose Arevalo
    Labels:
      - state-machine
      - athena-query
    SemanticVersion: 0.1.0

Resources:
##########################################################################
# IAM Role for StateMachine
##########################################################################
  DataProcessingStateMachineRole:
    Type: AWS::IAM::Role
    Properties:
      RoleName: latana.role.serverless-data-pipe.state-machine
      AssumeRolePolicyDocument:
        Version: '2012-10-17'
        Statement:
          - Effect: Allow
            Principal:
              Service: states.amazonaws.com
            Action: sts:AssumeRole
      ManagedPolicyArns:
        - arn:aws:iam::aws:policy/CloudWatchFullAccess
        - arn:aws:iam::aws:policy/AmazonS3FullAccess
        - arn:aws:iam::aws:policy/AmazonAthenaFullAccess

##########################################################################
# State Machine
##########################################################################
  AthenaQueriesStateMachine:
    Type: AWS::StepFunctions::StateMachine
    Properties:
      DefinitionUri: src/stm_star_query_execution.asl.json
      RoleArn: !GetAtt DataProcessingStateMachineRole.Arn
